# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.ssh.insert_key = false

  # config.vm.network "public_network", ip: "192.168.56.0", bridge: "eno1"

  config.vm.network :forwarded_port, guest: 22, host: 2222, host_ip: "0.0.0.0", id: "ssh", auto_correct: true

  config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.synced_folder ".", "/vagrant", disabled: true
  
  config.vm.provider :virtualbox do |v|
    v.memory = 2048
  end 
  # app.vm.hostname="doylestone03"

  # Ansible provisioner
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "main.yml"
  end


end
