# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"


  config.vm.network "private_network", ip: "192.168.56.0"
  config.vm.network "public_network", ip: "192.168.56.0", bridge: "eno1", auto_config: false

  config.vm.hostname = 'jenkins.howapped.dev'

  config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.synced_folder ".", "/vagrant", disabled: true
  
  config.vm.provider :virtualbox do |v|
    v.memory = 2048
  end 

  # Ansible provisioner
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "main.yml"
  end

  # default router
  config.vm.provision "shell",
    run: "always",
    inline: "ip route del default via 10.0.2.2 || true"  

  # running 'vagrant up' will provision so that you may
  # run `curl 192.168.56.0` on the vagrant host
  # to see the Jenkins login page

  # What do I need to run to be able to do the same
  # from another node in the LAN??


end
