- name: Download code-server legacy
  become: yes
  unarchive:
    remote_src: yes
    src: "{{ code_server_tar_url }}"
    dest: "{{ code_server_bin_dir }}"
    extra_opts:
      - --strip-components=1
      - --wildcards
      - "*/code-server"
  notify: Restart code-server
  when: code_server_download_needed
