############################################################################
#
#  Nix commands related to the local machine
#
############################################################################

deploy: 
	sudo nixos-rebuild switch --flake /etc/nixos#doylestone03