############################################################################
#
#  Nix commands related to the local machine
#
############################################################################

deploy: 
	nixos-rebuild switch --flake . --use-remote-sudo