---
- hosts: doylestone02
  vars_files:
    # Contains ansible_become_pass
    - inventory/group_vars/vault.yml

  become: yes
  pre_tasks:
    - debug:
        msg: "👷 Welcome! Provisioning {{ansible_nodename}} at {{ansible_default_ipv4['address']}} "

    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600

  roles:
    - base
    - docker
    - pallxk.code_server

  tasks:

    # - name: Install VScode-insiders # see: Geerling's breakdown of installing a package from web https://youtu.be/SLW4LX7lbvE?t=1610
